//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.02 at 06:09:20 PM IST 
//


package com.countryinfo.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CountryStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CapitalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countryStatus",
    "capitalStatus"
})
@XmlRootElement(name = "getCountryResponse")
public class GetCountryResponse {

    @XmlElement(name = "CountryStatus", required = true)
    protected String countryStatus;
    @XmlElement(name = "CapitalStatus", required = true)
    protected String capitalStatus;

    /**
     * Gets the value of the countryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryStatus() {
        return countryStatus;
    }

    /**
     * Sets the value of the countryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryStatus(String value) {
        this.countryStatus = value;
    }

    /**
     * Gets the value of the capitalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapitalStatus() {
        return capitalStatus;
    }

    /**
     * Sets the value of the capitalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapitalStatus(String value) {
        this.capitalStatus = value;
    }

}
